version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: blogs-r-us-web
    ports:
      - '80:80'
    volumes:
      - ./src:/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blogs-r-us-network
    depends_on:
      - php
  php:
    container_name: blogs-r-us-php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
        - ./src:/src
    networks:
      - blogs-r-us-network
    depends_on:
      - db
  db:
    container_name: blogs-r-us-db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: n0h4cksmydbplz
      MYSQL_DATABASE: blogsrus
    ports:
      - '3306:3306'
    networks:
      - blogs-r-us-network
  
networks:
  blogs-r-us-network:
    driver: bridge
  